//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
)

type Link struct {
	ID        uuid.UUID `sql:"primary_key"`
	RecordID  uuid.UUID
	RecordId2 uuid.UUID
	Strength  int16
}
