//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type RecordHistory struct {
	ID           uuid.UUID `sql:"primary_key"`
	RecordID     *uuid.UUID
	Title        string
	Description  string
	Location     *string
	Significance *string
	URL          string
	StartDate    *time.Time
	EndDate      *time.Time
	Type         int16
	Status       int16
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
