// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: commands.sql

package data

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createRecord = `-- name: CreateRecord :one
insert into record (title, description, location, significance, url, start_date, end_date, status, type)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
returning id, title, description, location, significance, url, start_date, end_date, type, status
`

type CreateRecordParams struct {
	Title        string
	Description  string
	Location     sql.NullString
	Significance sql.NullString
	Url          string
	StartDate    sql.NullTime
	EndDate      sql.NullTime
	Status       int16
	Type         int16
}

func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams) (Record, error) {
	row := q.db.QueryRowContext(ctx, createRecord,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.Significance,
		arg.Url,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.Type,
	)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Significance,
		&i.Url,
		&i.StartDate,
		&i.EndDate,
		&i.Type,
		&i.Status,
	)
	return i, err
}

const updateRecord = `-- name: UpdateRecord :exec
update record
set title = $2, description = $3, location = $4, significance = $5, url = $6, start_date = $7, end_date = $8, status = $9
where id = $1
`

type UpdateRecordParams struct {
	ID           uuid.UUID
	Title        string
	Description  string
	Location     sql.NullString
	Significance sql.NullString
	Url          string
	StartDate    sql.NullTime
	EndDate      sql.NullTime
	Status       int16
}

func (q *Queries) UpdateRecord(ctx context.Context, arg UpdateRecordParams) error {
	_, err := q.db.ExecContext(ctx, updateRecord,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.Significance,
		arg.Url,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
	)
	return err
}
