// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package data

import (
	"database/sql"
	"time"
)

type Impact struct {
	ID        string
	SubjectID string
	Reasoning string
	Category  string
	Value     int64
}

type ImpactRevision struct {
	ID       string
	ImpactID string
}

type SchemaMigration struct {
	Version string
}

type Subject struct {
	ID          string
	Title       string
	Summary     string
	SubjectType sql.NullString
	Url         string
	Weight      sql.NullInt64
	FromDate    time.Time
	UntilDate   time.Time
}

type SubjectRelation struct {
	Subject1 sql.NullString
	Subject2 sql.NullString
}
