// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package data

import (
	"database/sql"

	"github.com/google/uuid"
)

type Impact struct {
	ID          uuid.UUID
	RecordID    uuid.NullUUID
	Description string
	Value       int16
	Category    int16
}

type Link struct {
	ID        uuid.UUID
	RecordID  uuid.NullUUID
	RecordId2 uuid.NullUUID
	Strength  int16
}

type Record struct {
	ID           uuid.UUID
	Title        string
	Description  string
	Location     sql.NullString
	Significance sql.NullString
	Url          string
	StartDate    sql.NullTime
	EndDate      sql.NullTime
	Type         int16
	Status       int16
}

type SchemaMigration struct {
	Version string
}

type Source struct {
	ID          uuid.UUID
	RecordID    uuid.NullUUID
	Title       string
	Type        int16
	Url         string
	Description sql.NullString
}
