// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package data

import (
	"context"

	"github.com/google/uuid"
)

const getRecord = `-- name: GetRecord :one
select id, title, description, location, significance, url, start_date, end_date, type, status from record where id = $1
`

func (q *Queries) GetRecord(ctx context.Context, id uuid.UUID) (Record, error) {
	row := q.db.QueryRowContext(ctx, getRecord, id)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Significance,
		&i.Url,
		&i.StartDate,
		&i.EndDate,
		&i.Type,
		&i.Status,
	)
	return i, err
}

const getRecords = `-- name: GetRecords :many
select id, title, description, location, significance, url, start_date, end_date, type, status from record
`

func (q *Queries) GetRecords(ctx context.Context) ([]Record, error) {
	rows, err := q.db.QueryContext(ctx, getRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Record
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.Significance,
			&i.Url,
			&i.StartDate,
			&i.EndDate,
			&i.Type,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
